export enum ActionTypes {
    ACTION_ORDER_ID = "ACTION_ORDER_ID",
    ACTION_STATUS = "ACTION_STATUS",
    ADD_ORDER = "ADD_ORDER",
    ADD_ORDER_DETAIL = "ADD_ORDER_DETAIL",

    CLEAR_ORDER_DETAIL = "CLEAR_ORDER_DETAIL",

    DELETE_ORDER_DETAIL = "DELETE_ORDER_DETAIL",
    DELETE_ORDERMASTER_LISTS = "DELETE_ORDERMASTER_LISTS",
    DELETE_DATA = "DELETE_DATA",

    INSERT_DATA = "INSERT_DATA",
    
    UPDATE_QUANTITY = "UPDATE_QUANTITY",
    UPDATE_ORDER = "UPDATE_ORDER",

    TEST = "TEST"
}